app:
  name: "Calendar"

server:
  address: "127.0.0.1"
  port: 8080
  tls:
    enabled: false
    cert_file: "cert.pem"
    key_file: "key.pem"

logger:
  level: "info"
  file: "logs/app.log"

database:
  workmode: postgresql    # memory/postgresql
  postgresql:
    dsn: "" # если dsn = "" используются параметры подключения ниже
    user: "cl_admin"
    password: "admin1"
    host: "localhost"
    port: 5432
    name: "calendar"
    pool:
      # Макс. число открытых соединений от этого процесса (по умолчанию - 20)
      max_open_conns: 20
      # Макс. число открытых неиспользуемых соединений (по умолчанию - 10)
      max_idle_conns: 10
      # Макс. время жизни одного подключения (time.Duration)(по умолчанию - 1h)
      conn_max_lifetime: "1h" 
      # Макс. время ожидания подключения в пуле (time.Duration))(по умолчанию - 10m)
      conn_max_idle_time: "10m"


rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue: "calendar_events"

scheduler:
  enabled: true
  interval: "1m"
